wandb_version: 1

alpha:
  value: 0.05
episodes:
  value: 20000
eps_decay:
  value: 0.9995
eps_end:
  value: 0.05
eps_start:
  value: 0.9
steps:
  value: 300
tau_end:
  value: 0.2
tau_start:
  value: 3
