wandb_version: 1

alpha:
  value: 0.1
episodes:
  value: 10000
eps_decay:
  value: 0.9997
eps_end:
  value: 0.01
eps_start:
  value: 0.8
steps:
  value: 1000
tau_end:
  value: 0.1
tau_start:
  value: 2
