_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 12
                - 45
                - 55
            "2":
                - 12
                - 45
                - 55
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
alpha:
    value: 0.2
episodes:
    value: 20000
eps_end:
    value: 0.05
eps_start:
    value: 0.8
