wandb_version: 1

alpha:
  value: 0.2
episodes:
  value: 10000
eps_decay:
  value: 0.9997
eps_end:
  value: 0.01
eps_start:
  value: 0.5
steps:
  value: 200
tau_end:
  value: 0.3
tau_start:
  value: 1
