_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 14
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
alpha:
    value: 0.05
episodes:
    value: 10000
steps:
    value: 1000
tau_end:
    value: 0.02
tau_start:
    value: 3
